---

- include: php56.yml
- include: php70.yml
- include: php71.yml

- name: Install PECL modules
  command: pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "'already installed' not in pecl_result.stdout and 'completed successfully' not in pecl_result.stdout"
  with_items:
    - yaml

- name: Install PEAR modules
  command: pear install {{ item }}
  register: pear_result
  changed_when: "'already installed' not in pear_result.stdout"
  failed_when: "'already installed' not in pear_result.stdout and 'install ok' not in pear_result.stdout"
  with_items:
    - PHP_CodeSniffer

- name: Install WordPress code sniffs
  git:
    repo: git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
    dest: /usr/share/php/wpcs
    update: yes
    accept_hostkey: yes

- name: Enable WordPress code sniffs
  command: phpcs --config-set installed_paths /usr/share/php/wpcs
  
# Set the alternatives deliberately, so the later versions don't override
- name: Set PHP 7.1 bin as default
  alternatives: name=php link=/usr/bin/php path=/usr/bin/php7.1

- name: Set PHP 7.1 config as default
  alternatives: name=php-config link=/usr/bin/php-config path=/usr/bin/php-config7.1

- name: Set PHP 7.1 ize as default
  alternatives: name=phpize link=/usr/bin/phpize path=/usr/bin/phpize7.1
