---

- name: Enable Ondrej PHP repo
  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_lsb.codename }} main' state=present

- name: Install PHP 7.0 packages
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
      - php7.0-common
      - php7.0-cli
      - php7.0-curl
      - php7.0-dev
      - php7.0-gd
      - php7.0-fpm
      - php7.0-json
      - php7.0-opcache
      - php7.0-mbstring
      - php7.0-mysql
      - php7.0-xml
      - php-memcached
      - php-xdebug

- name: Push out 7.0 php.ini file
  template:
    src: etc/php/7.0/fpm/php.ini
    dest: /etc/php/7.0/fpm/php.ini
  notify: php7.0-fpm restart

- name: Set the max file upload size
  ini_file:
    dest: /etc/php/7.0/fpm/php.ini
    section: "PHP"
    option: "{{ item }}"
    value: "{{ file_upload_max_size }}M"
  with_items:
    - upload_max_filesize
    - post_max_size
  notify: php7.0-fpm restart

- name: Set 7.0 values in php.ini cli
  ini_file:
    dest: /etc/php/7.0/cli/php.ini
    section: "PHP"
    option: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'short_open_tag', value: 'On' }
  notify: php7.0-fpm restart
