- name: "Provision {{ enviro }} WP Databases"
  mysql_db: name="wpe_{{ enviro }}" state=present

- name: "Grant {{ enviro }} WP users access to WP DBs"
  mysql_user: name="wpe_{{ enviro }}" priv="wpe_{{ enviro }}.*:ALL" host="%" password=wordpress state=present

- name: "Grant {{ enviro }} WP users access to WP DBs"
  mysql_user: name="wpe_{{ enviro }}" priv="wpe_{{ enviro }}.*:ALL" host="localhost" password=wordpress state=present

- name: "Set up {{ enviro }} docroot"
  file: path={{ wp_doc_root }}/{{ enviro }} state=directory owner={{ web_user }} group={{ web_group }}

- name: "Download and install WordPress for {{ enviro }}"
  command: /usr/local/bin/wp core download --path={{ wp_doc_root}}/{{ enviro }}
  sudo: yes
  sudo_user: "{{ web_user }}"
  args:
    creates: "{{ wp_doc_root }}/{{ enviro }}/license.txt"

- name: Check whether {{ enviro }}/wp-config.php exists
  stat:
    path: "{{ wp_doc_root }}/{{ enviro }}/wp-config.php"
  register: wpconfig

- name: Fetch random salts for WordPress config
  get_url:
    dest: "{{ wp_doc_root }}/{{ enviro }}/wp-salts.php"
    url: https://api.wordpress.org/secret-key/1.1/salt/

- name: Make salts file a PHP file
  lineinfile:
    dest: "{{ wp_doc_root }}/{{ enviro }}/wp-salts.php"
    insertbefore: BOF
    line: <?php

- name: "Create wp-config for {{ enviro }}"
  template:
    src: wp/wp-config.php
    dest: "{{ wp_doc_root }}/{{ enviro }}/wp-config.php"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
  when: not wpconfig.stat.exists

- name: "Localconfig for {{ enviro }}"
  template: src=wp/local-config.php dest={{ wp_doc_root }}/{{ enviro }}/local-config.php owner={{ web_user }} group={{ web_group }}

- name: "Object Cache for {{ enviro }}"
  template: src=wp/object-cache.php dest={{ wp_doc_root }}/{{ enviro }}/wp-content/object-cache.php owner={{ web_user }} group={{ web_group }}

- name: "Check whether the WP install has been run previously"
  command: /usr/local/bin/wp core is-installed --path={{ wp_doc_root }}/{{ enviro }}
  sudo: yes
  sudo_user: "{{ web_user }}"
  ignore_errors: yes
  register: wpnotinstalled

- name: "Run the WP install for {{ enviro }}"
  command: /usr/local/bin/wp core install --url={{ domain }} --title="WP Engine {{ enviro }} Site" --admin_user=wordpress --admin_password=wordpress --admin_email="admin@example.com"
  sudo: yes
  sudo_user: "{{ web_user }}"
  args:
    chdir: "{{ wp_doc_root }}/{{ enviro }}"
  when: wpnotinstalled.rc

- name: "Install some useful plugins for {{ enviro }}"
  command: /usr/local/bin/wp plugin install {{ item }}
  sudo: yes
  sudo_user: "{{ web_user }}"
  with_items:
      - query-monitor
      - debug-objects
      - debug-queries
      - debug-bar
      - wordpress-importer
  args:
      chdir: "{{ wp_doc_root }}/{{ enviro }}"
      creates: "{{ wp_doc_root }}/{{ enviro }}/wp-content/plugins/{{ item }}"
